spring: #띄어쓰기 몹시 중요 !!!!! 많이 띄웠더니 h2 db에 적용이 안됐었음 띄어쓰기 없음
  datasource: # 2칸
    url: jdbc:h2:tcp://localhost/~/jpashop #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: #2칸
    hibernate: #4칸
      ddl-auto: create #6칸 #자동으로 이전 테이블을 드롭하고 새로 테이블 만들어주는 옵션
    properties:
      hibernate:
       # show_sql: true #8칸
        format_sql: true

logging.level: # 없음
  org.hibernate.SQL: debug #HIBERNATE 가 생성하는 SQL 이 모두 보이게됨 #2칸
# org.hibernate.type: trace
